baseURL = 'https://iccy.fun'
title = 'RunThem'
theme = 'm10c'

paginate = 12
publishDir = 'docs'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 2
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 3

[params]
  author = 'RunThem'
  avatar = 'images/N90.jpg'
  description = 'Hello C, Golang.'
  menu_item_separator = '<br>' # \n
  [[params.social]]
    icon = 'github'
    name = 'Github'
    url = 'https://github.com/runthem'
  [[params.social]]
    icon = 'mail'
    name = 'Mail'
    url = 'mailto:iccy.fun@outlook.com'

[markup.highlight]
  lineNos = true
  tabWidth = 2
    noClasses = true
  style = 'manni' # https://swapoff.org/chroma/playground

# My theme
[params.style]
  #bgImage = 'images/N90.jpg'
  darkestColor = '#135050'
  darkColor = '#212121'
  lightColor = '#d6d6d6'
  lightestColor = '#d3d3d3'
  primaryColor = '#ffffff'
